name: main branch auto ci process script
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.ref_name }} is learning GitHub Actions

on:
  push:
    branches: [main]

env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Github Actions IP 얻기
        id: ip
        uses: haythem/public-ip@v1.3

      - name: AWS Credentials(자격증명) 구성
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Github Actions IP to Security group(보안그룹) 추가
#        run: |
#          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
#        env:
#          AWS_DEFAULT_REGION: ap-northeast-2
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3에 zip 파일 업로드
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/peek-prod-code-deploy/$GITHUB_SHA.zip

      - name: S3에서 ZIP 파일 다운로드
        run: aws s3 cp s3://$S3_BUCKET_NAME/peek-prod-code-deploy/$GITHUB_SHA.zip ~/project.zip
#
      - name: 압축 해제
        run: unzip ~/project.zip -d ~/project
#
      - name: 프로젝트 디렉토리로 이동
        run: cd ~/project
#
#      - name: 의존성 설치
#        run: npm install
#
#      - name: 빌드 실행
#        run: npm run build
#
#      - name: 빌드 완료 메시지 출력
#        run: echo "Build completed successfully!"
#
#      - name: Github Actions IP From Security Group(보안그룹) 제거
#        run: |
#          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
#        env:
#          AWS_DEFAULT_REGION: ap-northeast-2
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

