name: main branch auto ci process script
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.ref_name }} is learning GitHub Actions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -al

      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files after checkout
        run: ls -al

      - name: List files in the current directory
        run: cat .github/workflows/deploy.yml

      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.REMOTE_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_SSH_PORT }}
            script: |
              echo "Deploying to remote server..."
              # Navigate to the project directory
              cd ~/ || exit 1
              
              pwd
              
              ls -a -l
              
              # Remove all contents in the directory
              rm -rf ~/peek-image-server
              
              git clone https://github.com/jm4293/peek-image-server.git
       
              pwd
              
              ls -a -l
            
              cd peek-image-server || exit 1
              
              pwd
              
              ls -a -l
                            
              # Install dependencies
              npm install
            
              # Install pm2 globally
              npm install -g pm2
                
              # Start the server using pm2
              pm2 start server.js --name peek-image-server
                
              echo "Deployment completed successfully!"

      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

