name: main branch auto ci process script
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.event.action }} is learning GitHub Actions

on:
  push:
    branches: [main]

#jobs:
#  deploy:
#    name: deploy
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_SSH_PORT }}
#          script: |
#            echo "Deploying to remote server..."
#            # Navigate to the project directory
#            cd /path/to/your/project || exit 1
#
#            # Pull the latest changes from the main branch
#            git pull origin main
#
#            # Install dependencies
#            npm install
#
#            # Build the project
#            npm run build
#
#            # Restart the server (if applicable)
#            pm2 restart your-app-name || exit 1
#
#            echo "Deployment completed successfully!"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/checkout.yml

